version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:10.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pg-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg-password}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./src/main/resources/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped