version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./src/main/resources/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql