server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 9090
    useServerHeader: true
    useForwardedHeaders: false
  gzip:
    enabled: false
  requestLog:
    appenders: []
target: https://user-info.herokuapp.com/users/
httpClient:
  timeout: 3s
  connectionTimeout: 10s
logging:
  loggers:
    "com.leonildo.cooperativism-vote-service": DEBUG

database:
  driverClass: org.postgresql.Driver

  user: pg-user

  password: pg-password

  url: jdbc:postgresql://localhost:5432/

  properties:
    charSet: UTF-8

  maxWaitForConnection: 1s

  validationQuery: "/* MyService Health Check */ SELECT 1"

  validationQueryTimeout: 3s

  minSize: 8

  maxSize: 32

  checkConnectionWhileIdle: false

  evictionInterval: 10s

  minIdleTime: 1 minute