package com.cooperativismvoteservice.core.repositoy;


import com.cooperativismvoteservice.core.dao.VotingAgendaDAO;
import com.cooperativismvoteservice.core.model.VotingAgenda;
import org.jdbi.v3.core.Jdbi;

import java.util.List;

public class VotingAgendaRepository implements VotingAgendaDAO {
    private final Jdbi jdbi;

    public VotingAgendaRepository(Jdbi jdbi) {
        this.jdbi = jdbi;
        this.jdbi.useHandle(handle -> handle.execute("CREATE TABLE IF NOT EXISTS voting_agenda " +
                "(voting_agenda_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "description varchar(2000) NOT NULL)"));
    }

    @Override
    public VotingAgenda findById(Long id) {
        return jdbi.withExtension(VotingAgendaDAO.class, dao -> dao.findById(id));
    }

    @Override
    public Long deleteById(Long voting_agenda_id) {
        return 0L;
    }

    @Override
    public Long insert(VotingAgenda votingAgenda) {
        return jdbi.withExtension(VotingAgendaDAO.class, dao -> dao.insert(votingAgenda));
    }

    @Override
    public List<VotingAgenda> getAll() {
        return jdbi.withExtension(VotingAgendaDAO.class, VotingAgendaDAO::getAll);
    }

}