package com.cooperativismvoteservice.core.dao.repositoy;

import com.cooperativismvoteservice.core.dao.VotingSessionDAO;
import com.cooperativismvoteservice.api.VotingSession;
import org.jdbi.v3.core.Jdbi;

import java.util.List;

public class VotingSessionRepository implements VotingSessionDAO {

    private final Jdbi jdbi;

    public VotingSessionRepository(Jdbi jdbi) {
        this.jdbi = jdbi;
        this.jdbi.useHandle(handle -> handle.execute("CREATE TABLE IF NOT EXISTS voting_session " +
                "(voting_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "voting_agenda_id BIGINT, start_time BIGINT, total_time BIGINT)"));
    }

    @Override
    public VotingSession findById(Long voting_session_id) {
        return jdbi.withExtension(VotingSessionDAO.class, dao -> dao.findById(voting_session_id));
    }

    @Override
    public Long deleteById(Long voting_session_id) {
        return 0L;
    }

    @Override
    public Long insert(VotingSession votingSession) {
        return jdbi.withExtension(VotingSessionDAO.class, dao -> dao.insert(votingSession));
    }

    @Override
    public List<VotingSession> getAll() {
        return jdbi.withExtension(VotingSessionDAO.class, VotingSessionDAO::getAll);
    }

    public Jdbi getJdbi() {
        return jdbi;
    }

}